### ISSUE TITLE
Eslint Integration

### ISSUE THREAD

**Issue by alexalikiotis** [nodeshift/oratrix#12]
@helio-frota @lholmquist  Maybe we should integrate eslint with this project for a more consistent code style. I have never set up eslint with TypeScript but I've seen other repos do it.

I also did find this GitHub repo https://github.com/dustinspecker/awesome-eslint#configs that lists eslint configs from big companies that we can use as a guide if we want

**Comment by helio-frota** [comment]
@alexalikiotis sounds good :+1:
