### ISSUE TITLE
Prettier trailingComma es5

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/oratrix#16]
@alexalikiotis I was looking the configuration of both prettier and tsconfig and I saw something 

trailing comma `ES5` https://github.com/nodeshift/oratrix/blob/master/.prettierrc#L4
tsconfig target `ES6` https://github.com/nodeshift/oratrix/blob/master/tsconfig.json#L3

I know that are two different things but looking the change log of prettier I found this
https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker

So seems we can remove this line https://github.com/nodeshift/oratrix/blob/master/.prettierrc#L4 ?

**Comment by alexalikiotis** [comment]
@helio-frota Yeah, It seems we can drop this option from the prettier config since it's the default behavior

**Comment by helio-frota** [comment]
landed https://github.com/nodeshift/oratrix/pull/18/commits/5392ceb460e5881d7590f4c1d8b5d4375ce1ac5d
