### ISSUE TITLE
Add files section before publish

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/oratrix#25]
@alexalikiotis I migrated a personal project from JS to TS to see what happen when we publish to npm and I saw that brakes:

```
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module './client'
Require stack:
```

This is the project : https://github.com/helio-frota/cli-chords

The way I found was to add the generated `build` directory in the files in package.json https://github.com/helio-frota/cli-chords/commit/e5866ef48a01783cd3a7433f700568683fede607

But we should take a look in other TS projects to see if they are publishing also the `src` directory (I believe yes) but since it is a CLI tool ... :man_shrugging:

**Comment by helio-frota** [comment]
I'm marking the "research" label again because that is not only to add the "build" in files section.
> ...we should take a look in other TS projects to see if they are publishing also the src directory (I believe yes) but since it is a CLI tool

**Comment by alexalikiotis** [comment]
@helio-frota This is the article that I found when I was on PTO https://medium.com/cameron-nokes/the-30-second-guide-to-publishing-a-typescript-package-to-npm-89d93ff7bccd

**Comment by helio-frota** [comment]
https://github.com/nodeshift/oratrix/commit/abda50ba89aae036bf8bd15c1fc1770780f37a5f
