### ISSUE TITLE
Public API and naming discussion

### ISSUE THREAD

**Issue by alexalikiotis** [nodeshift/oratrix#37]
This is a `discussion issue` about the public API that oratrix will expose to the end-users.

Currently, the API looks like this:
```
oratrix <command>

Commands:
  check     Searches for mandatory package.json fields
  licenses  Searches for licenses of the project.
```

One issue here (at least for me) is that the word `check` is a verb and the word `license` is a noun. Maybe it would be better to have as a convention the one over the other (better consistency - don't know which one would be better).

Another proposal is for us to go with something like this: `oratrix find-licenses` or `oratrix view-licenses` so we can verbalize the noun.

My concern about this one is that we have to be careful how we'll verbalize the noun because for example what if the future we decide to add a `--allow` flag that restricts what licenses can be used for a project. 

Then we'll have something like this: `oratrix view-licenses --allow MIT, Apache-2, ...` but then (at least for me) that will break the "word meaning" because `view-license` is a `view` process and a user does not expect any checks to be performed (or any errors to be thrown for this matter). 

By adding the `--allow` flag we migrated the command to a `check` command (based on some rules) but we're still using the `view-licenses` as the command name. (But this time errors might get thrown if the licenses don't meet some criteria)

Now maybe this is just me overthinking stuff...

**Comment by alexalikiotis** [comment]
Adding @helio-frota and @lholmquist so they can share their opinion. (If you think that's valuable you can add more team members for more feedback)

**Comment by helio-frota** [comment]
My main concern is to keep an easy path to track the development

Some examples:

`oratrix validate --> commands/ValidatorCmd --> core/Validator`
`oratrix find-licenses --> commands/LicenseFinderCmd --> core/LinceseFinder`

Other than that I'm good with any favorable name and just keeping the "path" to avoid something like:

`oratrix report --> commands/LogCmd --> core/StdoutReportHandler`

Also because we are using `Cmd` suffix to make difference between `commands` and the "business" logic that should reside in `core` directory

**Comment by lholmquist** [comment]
I like `validate` instead of check.    I would also try to keep what ever the word is a one word non hyphenated thing.  it is just easier to type

**Comment by helio-frota** [comment]
> I would also try to keep what ever the word is a one word non hyphenated thing. it is just easier to type

Yeah I agree.

That's why I choose `licenses`

To also match with `commands/licensesCmd.ts` and `core/licenses.ts`

```
Commands:
  cli.js check     Searches for mandatory package.json fields
  cli.js licenses  Searches for licenses of the project.
```

**Comment by helio-frota** [comment]
I also think we should refactor license-reporter to TS and call it `lr` : )

**Comment by alexalikiotis** [comment]
```
Commands:
  cli.js validate     Searches for mandatory package.json fields
  cli.js licenses     Searches for licenses of the project.
```
LGTM cause we can later add whatever we want to licenses and we won't break the "word meaning".

We still have `verbs` and `nouns` as commands but I think it's ok for now
