### ISSUE TITLE
Publish 0.0.1

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/oratrix#51]
We need to publish a 0.0.1 version and see how it works.
@alexalikiotis the idea is for you to publish but since we may have some issues I'm assigning for me also.

Depends on #31

**Comment by alexalikiotis** [comment]
@helio-frota @lholmquist I think we're ready for the v0.0.1 release.
If I'm forgetting anything please let me know.

**Comment by helio-frota** [comment]
@alexalikiotis I think it would be good to fix the tests before publishing, other than that LGTM :+1:

**Comment by alexalikiotis** [comment]
@helio-frota I will try to fix the tests today and tomorrow and we can publish the v0.0.1 release on Monday

**Comment by helio-frota** [comment]
@alexalikiotis sounds great :+1:

**Comment by alexalikiotis** [comment]
It's official https://www.npmjs.com/package/oratrix
