### ISSUE TITLE
Discuss what are the mandatory/required fields

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/oratrix#6]
Currently we added this just to represent the idea https://github.com/nodeshift/oratrix/blob/master/src/util/fields.json.

**Comment by helio-frota** [comment]
So discussing with @lholmquist I think we are good on this. And we can move one for now.

**Comment by dhladky** [comment]
Definitely license information should be mandatory.

**Comment by helio-frota** [comment]
@dhladky Thanks we are going to add that :+1:

**Comment by helio-frota** [comment]
https://github.com/nodeshift/oratrix/issues/10
