### ISSUE TITLE
Refactoring classes with exported functions

### ISSUE THREAD

**Issue by alexalikiotis** [nodeshift/oratrix#68]
After the end of development from @helio-frota and myself so we can bring oratrix to its first release I had some time to retrospect the code we've written.  Watching the code now, my main concern is that we use classes all over the place and that will introduce bottlenecks down the road.

**1** => ES2015 classes are not implemented in the language itself but it's just syntax sugar for something called "prototype inheritance" (see https://javascript.info/prototype-inheritance). So we should not think of them as regular classes similar to other languages like JAVA, C++, etc.

**2** => I think oratrix's project structure gives us a good opportunity to separate concerns and it's really easy to add new features down the road. Using classes though adds more code than necessary (in my opinion) without offering something helpful.

#### For example:

With classes:

```js
class GithubFetcher {
 
  async getRepositories(...) {
     ...
  }

  async hasPackageJSON(...) {
     ...
  }

  async fetch(...) {
     ...
  }

}

export default GithubFetcher;
```

With functions:

```js
export const getRepositories = () => { ... };

export const hasPackageJSON = () => { ... };

export const fetch = () => { ... };
```

Less code is required and we don't need to instantiate a new object every time we need to use the github-fetcher utility.

**3** => Testing and especially mocking these classes sometimes gets tricky.

For example:

```js
// ClassA.ts

class A {

   async someFunction() { ... }

}

// ClassB.ts

import A from 'ClassA.ts'

class B {

   async someOtherFunction () {

      const variable = new A().someFunction();
      
      // other code

   }

}
```

Mocking the **someFunction** (while testing ClassB) with a mocking library like `sinon` or `proxyquire` seems impossible or I haven't found a way to do that yet. (so that reduces our test coverage).

@helio-frota and @lholmquist I would really like to hear your opinions about this and if it makes sense in the future to refactor classes with just exported functions. (and @lholmquist don't worry all of the above has nothing to do with TypeScript 😅)

**Comment by helio-frota** [comment]
@alexalikiotis good write up :+1:  I think we should /cc  @wtrocki to also have input on that

**Comment by wtrocki** [comment]
I'm not sure if that actually makes difference for me personally. I use functions when there is logical sense to create stateful solution - there is need for instance etc. This is also simplifying mocking etc. I will struggle to address this concern without going into the canons of objective vs functional programing thus being opiniated about the whole case. 

This is the CLI, Codebase looks very very simple. By the end of the day keeping things consistent is more relevant than keeping things aligned with some use cases. 

---------
Opiniated response

For this case class seems like good choice.

**Comment by alexalikiotis** [comment]
First of all, I wanna start by saying that this is just a discussion and every opinion is accepted.

My own view is that using classes makes sense when you need multiple instances of something, for example, a database client should be a class because an app may need multiple clients to point to different databases (so multiple client instances). When you need to use something once in your app, then using functions makes more sense (personal opinion).

Anyway, you don't have to do anything about this, we are just having a discussion about the best approach moving forward. 🙂

**Comment by lholmquist** [comment]
I'm more partial to just using functions,   but as long as the code base is consistent, then it doesn't really matter.

**Comment by helio-frota** [comment]
@lholmquist I think the same :+1:

**Comment by alexalikiotis** [comment]
I'm on the same boat with you guys, just keep in mind that now that the project is still small this refactoring (classes -> functions) won't take that long (1-2 days tops) if we decide to do it.

**Comment by wtrocki** [comment]
I guess go for it and ping me for review

**Comment by alexalikiotis** [comment]
Yeah sure, I can open a draft PR with the changes and see how it looks, and then we can decide 🙂

**Comment by alexalikiotis** [comment]
Hi all, this is the draft for 'classes to functions' migration: https://github.com/nodeshift/oratrix/tree/class-to-function.

Now I can also increase the test coverage to nearly 100% because I'm able to write tests targeting the GitHub org validator. (not implemented yet on this draft but it'll be soon).

@helio-frota @wtrocki @lholmquist tell me what you think.

**Comment by helio-frota** [comment]
@alexalikiotis so I already look earlier the branch,  and already approved the PR : )
