### ISSUE TITLE
assert.equal seems to be @deprecated

### ISSUE THREAD

**Issue by alexalikiotis** [nodeshift/oratrix#7]
@helio-frota When I look into the test folder my IDE (vscode) says the following when hovering over assert.equal

> @deprecated — since v9.9.0 - use strictEqual() instead.

**Comment by helio-frota** [comment]
You right, this is showing for me.

![2020-09-17_06-55](https://user-images.githubusercontent.com/6443576/93455581-e6e73280-f8b2-11ea-8aba-0f5bfa66fdf0.png)

Yesterday I ran "sudo dnf update" on fedora 32 and it updated vscode but I was looking other 
code instead oratrix.

Also something wrong happened with laptop webcam during meeting with @balunasj 

Anyway can you please send a PR to fix? 
Thanks

**Comment by helio-frota** [comment]
Related to https://github.com/nodeshift/oratrix/pull/8
