### ISSUE TITLE
Investigate the possibility to have licenses information 

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/oratrix#9]
This is a general issue title, we need to know what is good for this project to display information about licenses... for example if we want just to display the licenses of each dependency + the project itself. Or if we want to expand the scope and start looking for licenses conflicts kind of thing.

**Comment by helio-frota** [comment]
I found some information related to the "unified list". That is a list of approved and disapproved licenses. 
In license-reporter we get the licenses of a project `Foo` and its dependencies, and we search/compare with the 
"unified list". That is done in license-reporter to show something like this:

```
Foo project has the following: 
Approved licenses:
...
Disapproved licenses:
...
Clarification advised:
...
```

We are planning if running oratrix in CI and License-reporter is more like an informative tool...so maybe makes no much sense to print out much information to stdout ?

Other thing is, we have an archived project called szero that we implemented a feature just to show the licenses using a basic API exposed from license-repoter:

```
$ szero . -l
------------------------------------------------------------
[ Licenses ]
------------------------------------------------------------
axios -> MIT License
cli-table3 -> MIT License
yargs -> MIT License
```

**Comment by helio-frota** [comment]
Running szero on nodeshift for example, we have the following:

```
chalk -> MIT License
js-yaml -> MIT License
minimatch -> ISC License
openshift-rest-client -> Apache License 2.0
parse-gitignore -> MIT License
tar -> ISC License
```

After to change `node_modules/chalk/package.json` manually from `MIT` to `MMIT` , it shows `UNKNOWN` (as expected) :

```
chalk -> UNKNOWN
js-yaml -> MIT License
minimatch -> ISC License
openshift-rest-client -> Apache License 2.0
parse-gitignore -> MIT License
tar -> ISC License
```

This is the code to have the result above:

```
const licenseReporter = require('license-reporter');
licenseReporter.licenses(dir, false);
```

So we have a situation here... 

a) to import and change/adapt license-reporter ( easy way ) 
b)  re-implement only that feature in oratrix with TS.

I vote a) :+1:  :smile:

**Comment by helio-frota** [comment]
> a) to import and change/adapt license-reporter ( easy way )

:thinking: maybe not so easy because license-reporter was designed for RHT products then the idea of "approved/disapproved" licenses can not be applied in general ? (I have no idea).
Also other thing is that API call is suppressing (running, but suppressing) this information:
```
Approved licenses:
Disapproved licenses:
Clarification advised:
```
Which implies that we have code doing things that makes no sense for oratrix so :man_shrugging: 

Probably we need to use https://www.npmjs.com/package/license-checker directly and to decide what to do with the licenses found.

**Comment by helio-frota** [comment]
When using license-checker + @types/license-checker I'm getting undefined for module name:

```
[
  { name: undefined, licenses: 'MIT' },
  { name: undefined, licenses: 'MIT' },
  { name: undefined, licenses: 'ISC' },
  { name: undefined, licenses: 'MIT' },
...
```

**Comment by helio-frota** [comment]
Adding some extra information for us to think later.
When we use the option `onlyAllow` we can pass a list of licenses separated by semicolon: `MIT;ISC`

But that way, license-checker throws error and we don't have access to that.
This is the following error message:

```
Package "license-checker@25.0.1" is licensed under "BSD-3-Clause" which is not permitted by the --onlyAllow flag. Exiting.
```

So I think we should not use `onlyAllow`, and handle the error message and rules related to it in our way.

**Comment by alexalikiotis** [comment]
@helio-frota so what should be the oratrix's behavior for the licenses ??

1. Just print them in a table kind of style ??
2. Add license restrictions ??
3. Something else ??

**Comment by helio-frota** [comment]
@alexalikiotis I think we should ask @mhdawson 

@mhdawson what do you think we have this feature this way for now ?

`oratrix licenses --allows=MIT,ISC`

Then in case "FooBar" license found, we show a warning message to stdout.

And this way:

`oratrix licenses --allows=MIT,ISC --ci=true`

In case "FooBar" license found, we exit and break the build 

Please let us know if that makes sense as starting feature :+1:

**Comment by alexalikiotis** [comment]
Instead of `--ci=true` we can have a `--strict` flag and, when enabled oratrix will throw an error (otherwise a warning or something) if the license found it's not acceptable (if it's used in a CI this error will of course brake the build).

**Comment by helio-frota** [comment]
sound good to me, because we don't need to be in a "CI" environment to throw , user can decide to throw locally.

**Comment by mhdawson** [comment]
As mentioned in the meeting I think we should see what is already in place/available within Red hat in terms of licence scanning before going to far on this.  Otherwise something like that makes sense, although it may be more complicated as I think people use modifications of the licences so there may also need to be a way to allow specific licences (full text) as well

**Comment by helio-frota** [comment]
Sounds good.
We can also keep a really basic feature without much (or zero) rules for now.

**Comment by helio-frota** [comment]
I think we can close this issue for now.
We are kind of playing with license scanning and without strict rules.
One of the purpose of this issue was also for me to search information about what happened ~3 years ago with license-reporter and licenses.

So we can open another issue to discuss future ideas if needed :+1:
